name: .NET 8 CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ProductService.sln

    - name: Build
      run: dotnet build ProductService.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ProductService.Tests/ProductService.Tests.csproj --no-build --verbosity normal

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/yourapp:latest

  create-k8s-pr:
    name: Create PR with Kubernetes manifests
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create branch and add manifest
      run: |
        BRANCH="add-k8s-manifests-${{ github.run_number }}"
        git checkout -b $BRANCH

        mkdir -p k8s
        cat <<EOF > k8s/deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ProductService
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ProductService
          template:
            metadata:
              labels:
                app: ProductService
            spec:
              containers:
              - name: ProductService
                image: ${{ secrets.DOCKERHUB_USERNAME }}/ProductService:latest
                ports:
                - containerPort: 80
                env:
                - name: MONGODB__CONNECTIONSTRING
                  value: "mongodb://your-mongo-service:27017"
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: ProductService-service
        spec:
          selector:
            app: ProductService
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
          type: ClusterIP
        EOF

        git add k8s/deployment.yaml
        git commit -m "Add Kubernetes manifests"
        git push origin $BRANCH

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Add Kubernetes manifests"
        body: "This PR adds Kubernetes deployment and service manifests for your .NET 8 app with MongoDB."
        base: main
        branch: add-k8s-manifests-${{ github.run_number }}
