apiVersion: apps/v1
kind: Deployment
metadata:
  name: XPTO.ProductService
  labels:
    app: XPTO.ProductService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: XPTO.ProductService
  template:
    metadata:
      labels:
        app: XPTO.ProductService
    spec:
      containers:
      - name: XPTO.ProductService
        image: <DOCKERHUB_USERNAME>/XPTO.ProductService:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGODB__CONNECTIONSTRING
          value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: XPTO.ProductService-service
spec:
  selector:
    app: XPTO.ProductService
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
