version: '3.8'

services:
  mongo:
    image: mongo:8.0.9
    container_name: xpto-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  productservice:
    build: .
    container_name: xpto-product-service
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo_data:
